[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

